name = "Scientific"
license = "MIT"
licenselink = "https://github.com/leonidboykov/scientific-hugo-theme/blob/master/LICENSE"
description = "Clean theme for scientific laboratory"
homepage = "http://ailab.spb.ru/"
tags = ["academic", "blog"]
features = ["portfolio", "projects", "blog"]
min_version = "0.25.1"

[author]
  name = "Leonid Boykov"
  homepage = "https://leonidboykov.com"
